ARG BASE_JRE_IMAGE=eclipse-temurin:23-jre-alpine
ARG BASE_JDK_IMAGE=eclipse-temurin:23-jdk-alpine

#Stage 1: Dependencies
FROM ${BASE_JDK_IMAGE} AS dependencies
RUN apk add --no-cache maven
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline

#Stage 2: Build
FROM dependencies AS builder
COPY src ./src
RUN mvn clean package

#Stage 3: Runtime
FROM ${BASE_JDK_IMAGE} AS runtime
WORKDIR /app
VOLUME ["/app/logs"]
ARG JAR_FILE=*.jar
COPY --from=builder /build/target/${JAR_FILE} app.jar
ARG IMAGE_VERSION=1.0.0
LABEL author="Sergey Kargopolov" \
      org.opencontainers.image.version="${IMAGE_VERSION}" \
      org.opencontainers.image.title="Users Microservice" \
      org.opencontainers.image.description="Spring Boot service for managing users"
ENTRYPOINT ["java","-XX:MaxRAMPercentage=75.0","-jar","app.jar"]
#CMD ["--spring.profiles.active=test"]